-- Database
CREATE DATABASE AULA10;

-- Seta Database
USE AULA10;

-- Table Cliente
CREATE TABLE CLIENTE
( CODIGO INT AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY(CODIGO));

-- Insert Cliente
INSERT INTO CLIENTE
     VALUES (1,'CRISTIANO MARTINS NUNES','cmn@cmn.com.br');

-- Select Cliente
SELECT * FROM CLIENTE;
